### ISSUE TITLE
[Feature request] Rename in-container network devices to match the swarm network names 

### ISSUE THREAD

**Issue by muresan** [moby/libnetwork#1888]
For a stack like this:

```
services:
   myservice:
   networks:
     - mynet
networks:
   mynet:
```

Rename in-container network devices to match the swarm network names so instead of eth0,eth1,eth2 you would have mynet. This would assist with identification of devices/networks and would help with software that can bind to an interface.
If this is not possible, a mapping would also help, something like

```
services:
   myservice:
   networks:
     - mynet:eth0
networks:
   mynet:
```

Thanks.
