### ISSUE TITLE
Support QinQ networks

### ISSUE THREAD

**Issue by gcantho** [moby/libnetwork#2597]
Seems that macvlan_network.go does not support QinQ. Docker nativley supports this. When setting the parent to something like eth0.10.100 an error is thrown "Errorf("required interface name format is: name.vlan_id, ex. eth0.10 for vlan 10, instead received %s",  linkName)" from macvlan_setup.go parseVlan function. 

QinQ Seems to not be supported. Would be a Useful feature. Currently preventing me from implementing this libary. Is there a sugested work around?

**Comment by thaJeztah** [comment]
> Docker nativley supports this. 

docker is using libnetwork when you run "docker network create", or does that fail?

**Comment by gcantho** [comment]
It succeeds `docker network create -d macvlan --gateway=X.X.X.X --subnet=X.X.X.X/XX --ip_range=X.X.X.X/XX -o parent=eth0.20.200 vlan20-200` is the command I usually run. I have never had a problem with it.

**Comment by gcantho** [comment]
docker-compose is what is failing when I try and start this network in my yaml file
```
networks:
  qinq_network:
    driver: macvlan
      driver_opts:
        parent: eth0.20.200
      ipam:
        config:
          - subnet: X.X.X.X/XX
            gateway: X.X.X.X
            ip_range: X.X.X.X/XX
```
